### ISSUE TITLE
failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair

### ISSUE THREAD

**Issue by er1c-cartman** [TommyChangUMD/ros-humble-ros1-bridge-builder#3]
sorry for asking you again...
everything works well I guess.
for the last part, can you add tf too? not tf2
i mean here's the error I'm facing. I tried to subscribe tf from ros1 to ros2 on rviz, but this error is occurring

failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the --print-pairs option

Best regards

**Comment by er1c-cartman** [comment]
specially it's not subscribing odom related topics. because some tf values such as base_link, imu_link etc is subscribing, but like odom, camera_odom things aren't subscribable.
Hope it will be solved. 
For more specific description, I'm trying to subscribe ros1's topic to ros2. Trying to show on rviz on ros2 of ros1's topic

Best regards.

**Comment by TommyChangUMD** [comment]
Hi, Try running with ros1_bridge with the "--bridge-all-topics" option.

`$ ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
`

**Comment by er1c-cartman** [comment]
Hi.
yes I'm running with    
ros2 run ros1_bridge dynamic_bridge --bridge-all-topics

i think from ros2 to ros1, it works well, but from ros1 to ros2, it doesn't work specially with odom related 

I've checked with husky playpen and while running husky on ros1, ros2 couldn't subscribe odom tf
specially when I run rviz2, suddenly the odom's tf is gone
thanks for kind answering :)

Best regards.

**Comment by er1c-cartman** [comment]
well I'll upload tomorrow what it looks like in bridge terminal 
Best regards :)

**Comment by TommyChangUMD** [comment]
hmm.. I am not sure what might be the issue.   If it helps, the following pair shows how the odom messages are bridged:

```
$ ros2 run ros1_bridge dynamic_bridge --print-pairs | grep Od
  - 'nav_msgs/msg/Odometry' (ROS 2) <=> 'nav_msgs/Odometry' (ROS 1)

```

**Comment by er1c-cartman** [comment]
Yes it works like this.
home@home:~$ ros2 run ros1_bridge dynamic_bridge --print-pairs | grep Od
  - 'nav_msgs/msg/Odometry' (ROS 2) <=> 'nav_msgs/Odometry' (ROS 1)

But the problem I'm having right now is this.
When I run husky package on ros1 terminal and after run rosbridge, this is what I can see on terminal

home@home:~$ ros2 run ros1_bridge dynamic_bridge --bridge-all-topics 
created 1to2 bridge for topic '/camera/fisheye1/camera_info' with ROS 1 type 'sensor_msgs/CameraInfo' and ROS 2 type 'sensor_msgs/msg/CameraInfo'
created 1to2 bridge for topic '/camera/fisheye1/image_raw' with ROS 1 type 'sensor_msgs/Image' and ROS 2 type 'sensor_msgs/msg/Image'
created 1to2 bridge for topic '/camera/fisheye2/camera_info' with ROS 1 type 'sensor_msgs/CameraInfo' and ROS 2 type 'sensor_msgs/msg/CameraInfo'
created 1to2 bridge for topic '/camera/fisheye2/image_raw' with ROS 1 type 'sensor_msgs/Image' and ROS 2 type 'sensor_msgs/msg/Image'
created 1to2 bridge for topic '/camera/gyro/sample' with ROS 1 type 'sensor_msgs/Imu' and ROS 2 type 'sensor_msgs/msg/Imu'
created 1to2 bridge for topic '/camera/odom/sample' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/clock' with ROS 1 type 'rosgraph_msgs/Clock' and ROS 2 type 'rosgraph_msgs/msg/Clock'
created 1to2 bridge for topic '/diagnostics' with ROS 1 type 'diagnostic_msgs/DiagnosticArray' and ROS 2 type 'diagnostic_msgs/msg/DiagnosticArray'
created 1to2 bridge for topic '/husky_velocity_controller/cmd_vel' with ROS 1 type 'geometry_msgs/Twist' and ROS 2 type 'geometry_msgs/msg/Twist'
created 1to2 bridge for topic '/husky_velocity_controller/odom' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/imu/data' with ROS 1 type 'sensor_msgs/Imu' and ROS 2 type 'sensor_msgs/msg/Imu'
created 1to2 bridge for topic '/imu/data/bias' with ROS 1 type 'sensor_msgs/Imu' and ROS 2 type 'sensor_msgs/msg/Imu'
created 1to2 bridge for topic '/joint_states' with ROS 1 type 'sensor_msgs/JointState' and ROS 2 type 'sensor_msgs/msg/JointState'
created 1to2 bridge for topic '/kb_teleop/cmd_vel' with ROS 1 type 'geometry_msgs/Twist' and ROS 2 type 'geometry_msgs/msg/Twist'
created 1to2 bridge for topic '/navsat/fix' with ROS 1 type 'sensor_msgs/NavSatFix' and ROS 2 type 'sensor_msgs/msg/NavSatFix'
created 1to2 bridge for topic '/navsat/vel' with ROS 1 type 'geometry_msgs/Vector3Stamped' and ROS 2 type 'geometry_msgs/msg/Vector3Stamped'
created 1to2 bridge for topic '/odom' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/odometry/filtered' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/points' with ROS 1 type 'sensor_msgs/PointCloud2' and ROS 2 type 'sensor_msgs/msg/PointCloud2'
created 1to2 bridge for topic '/rosout' with ROS 1 type 'rosgraph_msgs/Log' and ROS 2 type 'rcl_interfaces/msg/Log'
created 1to2 bridge for topic '/rosout_agg' with ROS 1 type 'rosgraph_msgs/Log' and ROS 2 type 'rcl_interfaces/msg/Log'
created 1to2 bridge for topic '/tf_static' with ROS 1 type 'tf2_msgs/TFMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage'
created 1to2 bridge for topic '/twist_marker_server/cmd_vel' with ROS 1 type 'geometry_msgs/Twist' and ROS 2 type 'geometry_msgs/msg/Twist'
created 1to2 bridge for topic '/twist_marker_server/update' with ROS 1 type 'visualization_msgs/InteractiveMarkerUpdate' and ROS 2 type 'visualization_msgs/msg/InteractiveMarkerUpdate'
created 1to2 bridge for topic '/twist_marker_server/update_full' with ROS 1 type 'visualization_msgs/InteractiveMarkerInit' and ROS 2 type 'visualization_msgs/msg/InteractiveMarkerInit'
Created 2 to 1 bridge for service /camera/fisheye1/set_camera_info
Created 2 to 1 bridge for service /camera/fisheye2/set_camera_info
Created 2 to 1 bridge for service /ekf_localization/enable
Created 2 to 1 bridge for service /gazebo/pause_physics
Created 2 to 1 bridge for service /gazebo/reset_simulation
Created 2 to 1 bridge for service /gazebo/reset_world
Created 2 to 1 bridge for service /gazebo/unpause_physics
Created 2 to 1 bridge for service /imu/data/calibrate
[INFO] [1704416365.312643167] [ros_bridge]: Passing message from ROS 1 rosgraph_msgs/Clock to ROS 2 rosgraph_msgs/msg/Clock (showing msg only once per type)
[INFO] [1704416365.478210368] [ros_bridge]: Passing message from ROS 1 nav_msgs/Odometry to ROS 2 nav_msgs/msg/Odometry (showing msg only once per type)
[INFO] [1704416365.489626448] [ros_bridge]: Passing message from ROS 1 sensor_msgs/Imu to ROS 2 sensor_msgs/msg/Imu (showing msg only once per type)
[INFO] [1704416365.515987109] [ros_bridge]: Passing message from ROS 1 diagnostic_msgs/DiagnosticArray to ROS 2 diagnostic_msgs/msg/DiagnosticArray (showing msg only once per type)
[INFO] [1704416365.576237738] [ros_bridge]: Passing message from ROS 1 rosgraph_msgs/Log to ROS 2 rcl_interfaces/msg/Log (showing msg only once per type)
[INFO] [1704416365.576634801] [ros_bridge]: Passing message from ROS 1 tf2_msgs/TFMessage to ROS 2 tf2_msgs/msg/TFMessage (showing msg only once per type)
[INFO] [1704416365.577241164] [ros_bridge]: Passing message from ROS 1 visualization_msgs/InteractiveMarkerInit to ROS 2 visualization_msgs/msg/InteractiveMarkerInit (showing msg only once per type)
[INFO] [1704416365.959820587] [ros_bridge]: Passing message from ROS 1 sensor_msgs/Image to ROS 2 sensor_msgs/msg/Image (showing msg only once per type)
[INFO] [1704416365.961231153] [ros_bridge]: Passing message from ROS 1 sensor_msgs/CameraInfo to ROS 2 sensor_msgs/msg/CameraInfo (showing msg only once per type)
[INFO] [1704416366.017120428] [ros_bridge]: Passing message from ROS 1 visualization_msgs/InteractiveMarkerUpdate to ROS 2 visualization_msgs/msg/InteractiveMarkerUpdate (showing msg only once per type)
created 2to1 bridge for topic '/rosout' with ROS 2 type 'rcl_interfaces/msg/Log' and ROS 1 type 'rosgraph_msgs/Log'
[INFO] [1704416366.450071596] [ros_bridge]: Passing message from ROS 1 sensor_msgs/NavSatFix to ROS 2 sensor_msgs/msg/NavSatFix (showing msg only once per type)
[INFO] [1704416366.450142740] [ros_bridge]: Passing message from ROS 1 geometry_msgs/Vector3Stamped to ROS 2 geometry_msgs/msg/Vector3Stamped (showing msg only once per type)
[INFO] [1704416366.452109204] [ros_bridge]: Passing message from ROS 1 sensor_msgs/JointState to ROS 2 sensor_msgs/msg/JointState (showing msg only once per type)
[INFO] [1704416366.538913714] [ros_bridge]: Passing message from ROS 1 sensor_msgs/PointCloud2 to ROS 2 sensor_msgs/msg/PointCloud2 (showing msg only once per type)


but right after this, I run the rviz2 on ros2, this error is happening on ros1 terminal

failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option
created 2to1 bridge for topic '/clicked_point' with ROS 2 type 'geometry_msgs/msg/PointStamped' and ROS 1 type 'geometry_msgs/PointStamped'
created 2to1 bridge for topic '/goal_pose' with ROS 2 type 'geometry_msgs/msg/PoseStamped' and ROS 1 type 'geometry_msgs/PoseStamped'
created 2to1 bridge for topic '/initialpose' with ROS 2 type 'geometry_msgs/msg/PoseWithCovarianceStamped' and ROS 1 type 'geometry_msgs/PoseWithCovarianceStamped'
failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option
failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option
failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option


So i think when passing tf messages from ros1 to ros2, there's a problem. 
And the reason I told you the odom'f tf is not subscribing is when I see the ros2's rviz2's fixed frame and tf, it's not publishing the whole tf. specially tf related with odom. 

This is screen of rviz when I run husky package on ros1 
![image](https://github.com/TommyChangUMD/ros-humble-ros1-bridge-builder/assets/144649727/0f80a374-29d6-4581-a5e5-ff6fdcdba291)


And this is screen when I run rviz2 on ros2
![image](https://github.com/TommyChangUMD/ros-humble-ros1-bridge-builder/assets/144649727/5199a1c6-0679-4f4d-b420-ca5bd7a8f2c3)

As you see, there's no odom in ros2.

And the topic list, 
root@home:/# rostopic list 
/clicked_point
/clock
/cmd_vel
/diagnostics
/e_stop
/front/scan
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/performance_metrics
/gazebo/set_link_state
/gazebo/set_model_state
/goal_pose
/husky_velocity_controller/cmd_vel
/husky_velocity_controller/odom
/husky_velocity_controller/parameter_descriptions
/husky_velocity_controller/parameter_updates
/imu/data
/imu/data/accel/parameter_descriptions
/imu/data/accel/parameter_updates
/imu/data/bias
/imu/data/rate/parameter_descriptions
/imu/data/rate/parameter_updates
/imu/data/yaw/parameter_descriptions
/imu/data/yaw/parameter_updates
/initialpose
/joint_states
/joy_teleop/cmd_vel
/joy_teleop/joy
/joy_teleop/joy/set_feedback
/kb_teleop/cmd_vel
/navsat/fix
/navsat/fix/position/parameter_descriptions
/navsat/fix/position/parameter_updates
/navsat/fix/status/parameter_descriptions
/navsat/fix/status/parameter_updates
/navsat/fix/velocity/parameter_descriptions
/navsat/fix/velocity/parameter_updates
/navsat/vel
/odometry/filtered
/points
/rosout
/rosout_agg
/set_pose
/tf
/tf_static
/twist_marker_server/cmd_vel
/twist_marker_server/feedback
/twist_marker_server/update
/twist_marker_server/update_full


And this is ros2's topic list

home@home:~$ ros2 topic list 
/clicked_point
/clock
/diagnostics
/front/scan
/goal_pose
/husky_velocity_controller/cmd_vel
/husky_velocity_controller/odom
/imu/data
/imu/data/bias
/initialpose
/joint_states
/joy_teleop/cmd_vel
/joy_teleop/joy
/navsat/fix
/navsat/vel
/odometry/filtered
/parameter_events
/points
/rosout
/rosout_agg
/tf
/tf_static
/twist_marker_server/cmd_vel
/twist_marker_server/update
/twist_marker_server/update_full
home@home:~$ ros2 topic echo /tf

it's sometimes showing tf is publishing, but when I use echo to see it, it's not showing.
Also in bridge terminal, still showing this error
failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option

So i think there's a problem with porting tf from ros1 to ros2.

If you can, maybe you can try to run husky_playpen package in ros1 and check rviz2 on ros2. You will see the same problem with me i guess

Thanks for helping me solve the issue

Best regards.

**Comment by er1c-cartman** [comment]
Oh. and when I see the bridge terminal, it's only showing this
2 things are related with tf and it's these

created 1to2 bridge for topic '/tf_static' with ROS 1 type 'tf2_msgs/TFMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage'
[INFO] [1704418428.011715462] [ros_bridge]: Passing message from ROS 1 tf2_msgs/TFMessage to ROS 2 tf2_msgs/msg/TFMessage (showing msg only once per type)


So I guess the bridge is not porting tf...

And if it's porting, it's porting only once

**Comment by er1c-cartman** [comment]
And sometimes it works but when I turn on the rviz2, it stops
bridge terminal

created 1to2 bridge for topic '/tf' with ROS 1 type 'tf2_msgs/TFMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage'
created 1to2 bridge for topic '/tf_static' with ROS 1 type 'tf2_msgs/TFMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage'


bridge terminal after I run rviz2 or check ros2 topic echo /tf

failed to create 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option


Best regards

**Comment by TommyChangUMD** [comment]
I see.  Looks like the bridge know about

 **'tf2_msgs/TFMessage'** and ROS 2 type 'tf2_msgs/msg/TFMessage'

But not

**'tf/tfMessage'** and ROS 2 type 'tf2_msgs/msg/TFMessage':

Let me see if I can find the source code for "tf/tfMessage" and add it to Dockefile.

**Comment by er1c-cartman** [comment]
Thanks for the quick and caring answer :)
Wish you the best

**Comment by TommyChangUMD** [comment]
OK.  I updated the Dockerfile.   I should work now.

```
$ ros2 run ros1_bridge dynamic_bridge --print-pairs | grep tf
  - 'tf2_msgs/msg/TF2Error' (ROS 2) <=> 'tf2_msgs/TF2Error' (ROS 1)
  - 'tf2_msgs/msg/TFMessage' (ROS 2) <=> 'tf2_msgs/TFMessage' (ROS 1)
  - 'tf2_msgs/msg/TFMessage' (ROS 2) <=> 'tf/tfMessage' (ROS 1)
  - 'tf2_msgs/srv/FrameGraph' (ROS 2) <=> 'tf2_msgs/FrameGraph' (ROS 1)

```

**Comment by er1c-cartman** [comment]
Thanks for updating. But unfortunately, it's still not working :(
The bridge terminal is not showing errors anymore but still can't find the odom frame in ros2 :(

This is ros2 rviz2's screen

![image](https://github.com/TommyChangUMD/ros-humble-ros1-bridge-builder/assets/144649727/f42db05c-d96a-4644-84d0-682555f42c4e)

And this is ros1 rviz's screen

![image](https://github.com/TommyChangUMD/ros-humble-ros1-bridge-builder/assets/144649727/4d9456d3-8a5c-4b53-b11a-04d12d036fa9)


I guess the odom related thing isn't working that well... specially with tf
Anyway thanks for spending your time to solve the issue.

Best regards :)

**Comment by er1c-cartman** [comment]
And this is bridge terminal.
For me it isn't working well but your addition on tf is working

home@home:~$ ros2 run ros1_bridge dynamic_bridge --bridge-all-topics 
created 1to2 bridge for topic '/camera/fisheye1/camera_info' with ROS 1 type 'sensor_msgs/CameraInfo' and ROS 2 type 'sensor_msgs/msg/CameraInfo'
created 1to2 bridge for topic '/camera/fisheye1/image_raw' with ROS 1 type 'sensor_msgs/Image' and ROS 2 type 'sensor_msgs/msg/Image'
created 1to2 bridge for topic '/camera/fisheye2/camera_info' with ROS 1 type 'sensor_msgs/CameraInfo' and ROS 2 type 'sensor_msgs/msg/CameraInfo'
created 1to2 bridge for topic '/camera/fisheye2/image_raw' with ROS 1 type 'sensor_msgs/Image' and ROS 2 type 'sensor_msgs/msg/Image'
created 1to2 bridge for topic '/camera/gyro/sample' with ROS 1 type 'sensor_msgs/Imu' and ROS 2 type 'sensor_msgs/msg/Imu'
created 1to2 bridge for topic '/camera/odom/sample' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/clicked_point' with ROS 1 type 'geometry_msgs/PointStamped' and ROS 2 type 'geometry_msgs/msg/PointStamped'
created 1to2 bridge for topic '/clock' with ROS 1 type 'rosgraph_msgs/Clock' and ROS 2 type 'rosgraph_msgs/msg/Clock'
created 1to2 bridge for topic '/diagnostics' with ROS 1 type 'diagnostic_msgs/DiagnosticArray' and ROS 2 type 'diagnostic_msgs/msg/DiagnosticArray'
created 1to2 bridge for topic '/husky_velocity_controller/cmd_vel' with ROS 1 type 'geometry_msgs/Twist' and ROS 2 type 'geometry_msgs/msg/Twist'
created 1to2 bridge for topic '/husky_velocity_controller/odom' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/imu/data' with ROS 1 type 'sensor_msgs/Imu' and ROS 2 type 'sensor_msgs/msg/Imu'
created 1to2 bridge for topic '/imu/data/bias' with ROS 1 type 'sensor_msgs/Imu' and ROS 2 type 'sensor_msgs/msg/Imu'
created 1to2 bridge for topic '/initialpose' with ROS 1 type 'geometry_msgs/PoseWithCovarianceStamped' and ROS 2 type 'geometry_msgs/msg/PoseWithCovarianceStamped'
created 1to2 bridge for topic '/joint_states' with ROS 1 type 'sensor_msgs/JointState' and ROS 2 type 'sensor_msgs/msg/JointState'
created 1to2 bridge for topic '/kb_teleop/cmd_vel' with ROS 1 type 'geometry_msgs/Twist' and ROS 2 type 'geometry_msgs/msg/Twist'
created 1to2 bridge for topic '/move_base_simple/goal' with ROS 1 type 'geometry_msgs/PoseStamped' and ROS 2 type 'geometry_msgs/msg/PoseStamped'
created 1to2 bridge for topic '/navsat/fix' with ROS 1 type 'sensor_msgs/NavSatFix' and ROS 2 type 'sensor_msgs/msg/NavSatFix'
created 1to2 bridge for topic '/navsat/vel' with ROS 1 type 'geometry_msgs/Vector3Stamped' and ROS 2 type 'geometry_msgs/msg/Vector3Stamped'
created 1to2 bridge for topic '/odom' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/odometry/filtered' with ROS 1 type 'nav_msgs/Odometry' and ROS 2 type 'nav_msgs/msg/Odometry'
created 1to2 bridge for topic '/points' with ROS 1 type 'sensor_msgs/PointCloud2' and ROS 2 type 'sensor_msgs/msg/PointCloud2'
created 1to2 bridge for topic '/rosout' with ROS 1 type 'rosgraph_msgs/Log' and ROS 2 type 'rcl_interfaces/msg/Log'
created 1to2 bridge for topic '/rosout_agg' with ROS 1 type 'rosgraph_msgs/Log' and ROS 2 type 'rcl_interfaces/msg/Log'
created 1to2 bridge for topic '/tf' with ROS 1 type 'tf/tfMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage'
created 1to2 bridge for topic '/tf_static' with ROS 1 type 'tf2_msgs/TFMessage' and ROS 2 type 'tf2_msgs/msg/TFMessage'
created 1to2 bridge for topic '/twist_marker_server/cmd_vel' with ROS 1 type 'geometry_msgs/Twist' and ROS 2 type 'geometry_msgs/msg/Twist'
created 1to2 bridge for topic '/twist_marker_server/feedback' with ROS 1 type 'visualization_msgs/InteractiveMarkerFeedback' and ROS 2 type 'visualization_msgs/msg/InteractiveMarkerFeedback'
created 1to2 bridge for topic '/twist_marker_server/update' with ROS 1 type 'visualization_msgs/InteractiveMarkerUpdate' and ROS 2 type 'visualization_msgs/msg/InteractiveMarkerUpdate'
created 1to2 bridge for topic '/twist_marker_server/update_full' with ROS 1 type 'visualization_msgs/InteractiveMarkerInit' and ROS 2 type 'visualization_msgs/msg/InteractiveMarkerInit'
Created 2 to 1 bridge for service /camera/fisheye1/set_camera_info
Created 2 to 1 bridge for service /camera/fisheye2/set_camera_info
Created 2 to 1 bridge for service /ekf_localization/enable
Created 2 to 1 bridge for service /gazebo/pause_physics
Created 2 to 1 bridge for service /gazebo/reset_simulation
Created 2 to 1 bridge for service /gazebo/reset_world
Created 2 to 1 bridge for service /gazebo/unpause_physics
Created 2 to 1 bridge for service /imu/data/calibrate
Created 2 to 1 bridge for service /rviz/reload_shaders
[INFO] [1704437351.885713793] [ros_bridge]: Passing message from ROS 1 rosgraph_msgs/Clock to ROS 2 rosgraph_msgs/msg/Clock (showing msg only once per type)
[INFO] [1704437351.957468598] [ros_bridge]: Passing message from ROS 1 sensor_msgs/Image to ROS 2 sensor_msgs/msg/Image (showing msg only once per type)
[INFO] [1704437351.962906758] [ros_bridge]: Passing message from ROS 1 nav_msgs/Odometry to ROS 2 nav_msgs/msg/Odometry (showing msg only once per type)
[INFO] [1704437351.962992491] [ros_bridge]: Passing message from ROS 1 sensor_msgs/Imu to ROS 2 sensor_msgs/msg/Imu (showing msg only once per type)
[INFO] [1704437352.058700479] [ros_bridge]: Passing message from ROS 1 tf2_msgs/TFMessage to ROS 2 tf2_msgs/msg/TFMessage (showing msg only once per type)
[INFO] [1704437352.059866427] [ros_bridge]: Passing message from ROS 1 rosgraph_msgs/Log to ROS 2 rcl_interfaces/msg/Log (showing msg only once per type)
[INFO] [1704437352.060397315] [ros_bridge]: Passing message from ROS 1 visualization_msgs/InteractiveMarkerInit to ROS 2 visualization_msgs/msg/InteractiveMarkerInit (showing msg only once per type)
[INFO] [1704437352.069601012] [ros_bridge]: Passing message from ROS 1 visualization_msgs/InteractiveMarkerUpdate to ROS 2 visualization_msgs/msg/InteractiveMarkerUpdate (showing msg only once per type)
[INFO] [1704437352.072504937] [ros_bridge]: Passing message from ROS 1 sensor_msgs/JointState to ROS 2 sensor_msgs/msg/JointState (showing msg only once per type)
[INFO] [1704437352.073088687] [ros_bridge]: Passing message from ROS 1 tf/tfMessage to ROS 2 tf2_msgs/msg/TFMessage (showing msg only once per type)
[INFO] [1704437352.159360992] [ros_bridge]: Passing message from ROS 1 sensor_msgs/PointCloud2 to ROS 2 sensor_msgs/msg/PointCloud2 (showing msg only once per type)
[INFO] [1704437352.299476301] [ros_bridge]: Passing message from ROS 1 diagnostic_msgs/DiagnosticArray to ROS 2 diagnostic_msgs/msg/DiagnosticArray (showing msg only once per type)
[INFO] [1704437352.380982645] [ros_bridge]: Passing message from ROS 1 sensor_msgs/CameraInfo to ROS 2 sensor_msgs/msg/CameraInfo (showing msg only once per type)
created 2to1 bridge for topic '/clicked_point' with ROS 2 type 'geometry_msgs/msg/PointStamped' and ROS 1 type 'geometry_msgs/PointStamped'
created 2to1 bridge for topic '/goal_pose' with ROS 2 type 'geometry_msgs/msg/PoseStamped' and ROS 1 type 'geometry_msgs/PoseStamped'
created 2to1 bridge for topic '/initialpose' with ROS 2 type 'geometry_msgs/msg/PoseWithCovarianceStamped' and ROS 1 type 'geometry_msgs/PoseWithCovarianceStamped'
created 2to1 bridge for topic '/rosout' with ROS 2 type 'rcl_interfaces/msg/Log' and ROS 1 type 'rosgraph_msgs/Log'
[INFO] [1704437352.971774610] [ros_bridge]: Passing message from ROS 1 sensor_msgs/NavSatFix to ROS 2 sensor_msgs/msg/NavSatFix (showing msg only once per type)
[INFO] [1704437352.972270444] [ros_bridge]: Passing message from ROS 1 geometry_msgs/Vector3Stamped to ROS 2 geometry_msgs/msg/Vector3Stamped (showing msg only once per type)


Best regards :)

**Comment by er1c-cartman** [comment]
Or maybe it's not working well. I mean the bridge is working but it seems it's not getting the actual information.
I've checked with ros2 topic echo /tf, and the output is this

home@home:~$ ros2 topic echo /tf
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---
transforms: []
---


I'm not sure but it seems the tf isn't ported well.

Thanks for your work on my issues

Best regards :)

**Comment by TommyChangUMD** [comment]
Not sure if it helps, but looks like the same issue is reported here:
https://github.com/ros2/ros1_bridge/issues/219

**Comment by TommyChangUMD** [comment]
Do you have to use **camera_odom** TF when running ros2 rviz2?

Just a hunch, how about changing the **Global Options->Fixed Frame** to use **camera_odom_frame** instead of **camera_odom** ?

> Thanks for updating. But unfortunately, it's still not working :( The bridge terminal is not showing errors anymore but still can't find the odom frame in ros2 :(
> 
> This is ros2 rviz2's screen
> 
> ![image](https://private-user-images.githubusercontent.com/144649727/294415368-f42db05c-d96a-4644-84d0-682555f42c4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzkwNDUsIm5iZiI6MTcwNDQzODc0NSwicGF0aCI6Ii8xNDQ2NDk3MjcvMjk0NDE1MzY4LWY0MmRiMDVjLWQ5NmEtNDY0NC04NGQwLTY4MjU1NWY0MmM0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNzEyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTY0OTRlOWQ2OWM1NTNkMTdkZGQxNGZjODY4YWI0OThhZTY3MzlkMDU4ZjVmYjIzNDJjMjY5NmMyZGYzNmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u3RIll__pFxMI-AmFAtFOQUvHOhueGmRW2aJaY2IUoQ)
> 
> And this is ros1 rviz's screen
> 
> ![image](https://private-user-images.githubusercontent.com/144649727/294415474-4d9456d3-8a5c-4b53-b11a-04d12d036fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzkwNDUsIm5iZiI6MTcwNDQzODc0NSwicGF0aCI6Ii8xNDQ2NDk3MjcvMjk0NDE1NDc0LTRkOTQ1NmQzLThhNWMtNGI1My1iMTFhLTA0ZDEyZDAzNmZhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNzEyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmU0ZDRjZWRlMzdjNDVmNWZkNGI0ZTI1NDIwZDhjZWY4Y2UxYTZkMGJlNGY2YWMzZmJlZDA5NTJmYmI3MGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JpkK_yN5yHIKsKJKxTj0qbx9-rPkgm6k7IapGnhlssw)
> 
> I guess the odom related thing isn't working that well... specially with tf Anyway thanks for spending your time to solve the issue.
> 
> Best regards :)

**Comment by er1c-cartman** [comment]
well unfortunately, I have to use camera_odom. It's kind similar with odom, but using VO for using elevation mapping with traversability estimation. 
anyway camera_odom and odom tf isn't showing on rviz2 :(

sorry for not helping with your effort...

**Comment by er1c-cartman** [comment]
I see. Thanks for spending your time for helping me :)
i really appreciate it
I'll try bit differently to solve the issue
Again, thanks for helping me to solve the issue
Wish you a good luck with your research

Best regards :)

**Comment by TommyChangUMD** [comment]
Hi er1c-cartman, 

Can you try the latest Dockerfile? It might just work this time since I switched to using the pre-built binaries for tf and tf2.

**Comment by er1c-cartman** [comment]
well I've tried it but doesn't work.
same problem i think. like cannot bridge odom related tf
but thanks for spending your time 
and i decided to solve the problem with just do migration by myself on ros2 environment
Best regards :)
